
● Step 1: Represent three data samples as a (3 × features) NumPy matrix

In [3]:
import numpy as np

In [ ]:
X = np.array([[5, 8, 90],[3, 6, 80],[7, 10, 95]])
print(X)
print(X.shape)

[[ 5  8 90]
 [ 3  6 80]
 [ 7 10 95]]
(3, 3)


Step 2: Compute the dot product of one sample vector with a weight vector by hand, then verify it with
np.dot.

In [5]:
sample = X[0]
weights = np.array([2, 1.5, 0.1])
print(sample)
print( weights)

[ 5  8 90]
[2.  1.5 0.1]


In [7]:
prediction = np.dot(sample, weights)
print(prediction)

31.0


Step 3: Use matrix multiplication (@) to produce a prediction for all three samples at once

In [10]:
predictions = X @ weights
print(predictions)

[31.  23.  38.5]


Step 4: Deliberately create a shape-mismatch error, read the message, and explain in Markdown why it
occurred and how to fix it.

In [11]:
wrong_weights = np.array([2, 1.5])
wrong_predictions = X @ wrong_weights

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

How to interpret shape mismatch
The error occurred because the feature count of the matrix and the weights were not the same.
X matrix is (3, 3) so each sample has 3 features.
The wrong weight vector y is of shape (2,), meaning it contains just 2 weights.
Number of features = number of weights for the matrix muliplication.
The error is fixable with a weight vector with 3 values. 