# # Day 3 :


In [1]:
import numpy as np
data = np.array([10, 12, 12, 13, 100])
print(np.mean(data))
print(np.median(data)) 


29.4
12.0


In [2]:
import numpy as np
data = np.array([100, 110, 120, 130, 10])
print(np.mean(data))
print(np.median(data))

94.0
110.0


In [3]:
import numpy as np
v = np.array([25, 50000, 3]) 

In [4]:
print(v)

[   25 50000     3]


In [5]:
print(v.shape)

(3,)


In [1]:
import numpy as np

n = np.array([21, 88, 3])

print(n)

[21 88  3]


In [3]:
X = np.array([[25, 50000, 3],[40, 80000, 10],[33, 62000, 5]])
print(X.shape)

(3, 3)


In [4]:
X = np.array([[2, 3],[4,0],[3,8]])
print(X.shape)

(3, 2)


In [5]:
features = np.array([25, 50000, 3])
weights = np.array([0.1, 0.0002, 1.5])
prediction = np.dot(features, weights)

In [6]:
print(prediction)

17.0


In [7]:

features = np.array([5, 8, 90])

weights = np.array([2, 1.5, 0.1])

prediction = np.dot(features, weights)

print(prediction)

31.0


In [8]:
X = np.array([[25, 50000, 3], [40, 80000, 10]])
w = np.array([0.1, 0.0002, 1.5]) 
predictions = X @ w

In [9]:
print(predictions)

[17. 35.]


In [10]:

X = np.array([[5, 8, 90],[4, 6, 80],[7, 9, 95]])
w = np.array([2, 1.5, 0.1])
predictions = X @ w
print(predictions)

[31. 25. 37.]


In [15]:

X = np.array([[7,0],[4,0]])
w = np.array([2,5])
predictions = X @ w
print(predictions)

[14  8]


In [20]:
import numpy as np


In [21]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
print("Vector v1: ", v1)
print("Vector v2: ", v2)

Vector v1:  [1 2 3]
Vector v2:  [4 5 6]


In [23]:
v_add = v1 + v2
print(v_add)

[5 7 9]


In [24]:
dot_v = np.dot(v1,v2)
print(dot_v)

32


In [26]:
norm_v1 = np.linalg.norm(v1)
print(norm_v1)

3.7416573867739413


In [27]:
norm_v2 = np.linalg.norm(v2)
print(norm_v2)

8.774964387392123


In [29]:
A =  np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7,81]])
print("Matrix A:\n", A)
print("Matrix B:\n", B)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[ 5  6]
 [ 7 81]]


In [31]:
matrix_add = A + B
print(matrix_add)

[[ 6  8]
 [10 85]]


In [32]:

element_wise_mul = A * B
dot_product_matrix= np.dot(A, B)
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Element-wise multiplication (AB):\n", element_wise_mul)
print("Dot product of matrices (A, B):\n", dot_product_matrix)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[ 5  6]
 [ 7 81]]
Element-wise multiplication (AB):
 [[  5  12]
 [ 21 324]]
Dot product of matrices (A, B):
 [[ 19 168]
 [ 43 342]]


In [35]:
def matrix_multiplication(matrix1, matrix2):
    
    rows_matrix1 = len(matrix1)
    cols_matrix1 = len(matrix1[0])

    rows_matrix2 = len(matrix2)
    cols_matrix2 = len(matrix2[0])
    if cols_matrix1 != rows_matrix2:
        raise ValueError("Number of columns in Matrix1 must be equal to number of rows in Matrix2")
    result = [[0 for _ in range(cols_matrix2)] for _ in range(rows_matrix1)]
    for i in range(rows_matrix1):
        for j in range(cols_matrix2):
            for k in range(cols_matrix1):
                result[i][j] += matrix1[i][k] * matrix2[k][j]

    return result
    print(result)