# # DAY 3 == >Numpy

 Creating Arrays


In [6]:
import numpy as np

In [5]:
import numpy as np
kanto =np.array([73,67,43])

In [7]:
kanto

array([73, 67, 43])

In [8]:
type(kanto)

numpy.ndarray

In [9]:
kanto[0]

np.int64(73)

In [12]:
weights =np.array([3,6,4])

In [11]:
kanto * weights

array([5329, 4489, 1849])

In [13]:
(kanto * weights).sum()

np.int64(793)

In [15]:
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [19]:
z = np.zeros([2,3])
print(z)

[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
o = np.ones(5)
print(o)

[1. 1. 1. 1. 1.]


In [24]:
r = np.arange(0,10,2)
print(r)

[0 2 4 6 8]


In [25]:
r = np.arange(0,20,2)
print(r)

[ 0  2  4  6  8 10 12 14 16 18]


In [ ]:
r = np.arange(0,40,4)
print(r)

# القسم الاخير على كم الفسمة

[ 0  4  8 12 16 20 24 28 32 36]


In [28]:
l =np.linspace(0,1,5)
print(l)

[0.   0.25 0.5  0.75 1.  ]


In [33]:
l =np.linspace(0,1,100)
print(l)
# القسم الاخير عدد التقسيم بالتساوي

[0.         0.01010101 0.02020202 0.03030303 0.04040404 0.05050505
 0.06060606 0.07070707 0.08080808 0.09090909 0.1010101  0.11111111
 0.12121212 0.13131313 0.14141414 0.15151515 0.16161616 0.17171717
 0.18181818 0.19191919 0.2020202  0.21212121 0.22222222 0.23232323
 0.24242424 0.25252525 0.26262626 0.27272727 0.28282828 0.29292929
 0.3030303  0.31313131 0.32323232 0.33333333 0.34343434 0.35353535
 0.36363636 0.37373737 0.38383838 0.39393939 0.4040404  0.41414141
 0.42424242 0.43434343 0.44444444 0.45454545 0.46464646 0.47474747
 0.48484848 0.49494949 0.50505051 0.51515152 0.52525253 0.53535354
 0.54545455 0.55555556 0.56565657 0.57575758 0.58585859 0.5959596
 0.60606061 0.61616162 0.62626263 0.63636364 0.64646465 0.65656566
 0.66666667 0.67676768 0.68686869 0.6969697  0.70707071 0.71717172
 0.72727273 0.73737374 0.74747475 0.75757576 0.76767677 0.77777778
 0.78787879 0.7979798  0.80808081 0.81818182 0.82828283 0.83838384
 0.84848485 0.85858586 0.86868687 0.87878788 0.88888889 0.89898

In [34]:
rnd = np.random.rand(3,3)
print(rnd)

[[0.38494969 0.32159552 0.32655784]
 [0.69323344 0.34033506 0.57234736]
 [0.85060843 0.61988259 0.72860268]]


In [38]:

climate_data = np.array([[1,2,3],
                          [4,5,6],
                          [7,8,9],
                          [10,11,12],
                          [13,14,15]])
print(climate_data)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [39]:
climate_data.shape

(5, 3)

In [40]:
weights

array([3, 6, 4])

In [41]:
weights.shape

(3,)

In [44]:
arr3 = np.array([
                 [[11,12,13],
                 [13,14,15]],
                 [[15,16,17],
                 [17,18,18.5]]])
arr3.shape

(2, 2, 3)

In [45]:
arr3.dtype

dtype('float64')

In [46]:
weights.dtype

dtype('int64')

In [47]:
climate_data.dtype

dtype('int64')

In [48]:
np.matmul(climate_data,weights)

array([ 27,  66, 105, 144, 183])

In [49]:
climate_data @ weights

array([ 27,  66, 105, 144, 183])

3.3  Array Attributes, Indexing & Slicing


In [50]:
m = np.array([[1,2,3],[4,5,6]])
print(m)


[[1 2 3]
 [4 5 6]]


In [51]:
print(m.shape)

(2, 3)


In [52]:
print(m[0,2])

3


In [53]:
print(m[1,2])


6


In [54]:
print(m[:,1])


[2 5]


In [55]:
print(m[1,:])


[4 5 6]


-----------------------



In [57]:
arr1 = np.array([[1,2,3],[3,4,5]])
arr2 = np.array([[2,2,3],[1,2,5]])


In [58]:
arr1 == arr2

array([[False,  True,  True],
       [False, False,  True]])

In [59]:
arr1 != arr2

array([[ True, False, False],
       [ True,  True, False]])

In [60]:
arr1 >= arr2

array([[False,  True,  True],
       [ True,  True,  True]])

In [61]:
arr1 < arr2

array([[ True, False, False],
       [False, False, False]])

In [62]:
(arr1 == arr2).dtype

dtype('bool')

In [63]:
(arr1 < arr2).dtype

dtype('bool')

In [64]:
(arr1 == arr2).sum()

np.int64(3)

In [65]:
(arr1 == arr2).sum().dtype

dtype('int64')

In [67]:
 arr5 = np.array([
  [[11,12,13,14],
   [13,14,15,19]],
   [[15,16,17,21],
    [63,92,36,18]],
    [[98,32,81,23],
     [17,18,19.5,43]]
 ]
  
 )

In [68]:
arr5.shape

(3, 2, 4)

In [69]:
arr5[1,1]

array([63., 92., 36., 18.])

In [70]:
arr5[1,1,2]

np.float64(36.0)

In [71]:
arr5[1:,0:1,:2]

array([[[15., 16.]],

       [[98., 32.]]])

In [73]:
arr5[1]

array([[15., 16., 17., 21.],
       [63., 92., 36., 18.]])

In [75]:
b = np.zeros((3,2))

--------------------

3.4  Vectorized Operations

In [76]:
a = np.array([1,2,3,4])



In [77]:
print(a * 2)

[2 4 6 8]


In [78]:
print(a * a)

[ 1  4  9 16]


In [79]:
print(a.mean())

2.5


In [80]:
print(a.max())

4


In [81]:
print(a.min())

1


In [82]:
print(a[a > 2])

[3 4]


------------------------

In [83]:
import numpy as np

In [84]:
function1 = np.concatenate
function2 = np.max
function3 = np.min

---------------------------------------------

3.5  Broadcasting

In [85]:
matrix = np.array([[1,2,3],[4,5,6]])

In [86]:
row    = np.array([10, 20, 30])

In [88]:
print(matrix + row) 

[[11 22 33]
 [14 25 36]]


In [89]:
nn = np.array([[5,4,3],[4,5,6]])
mm = np.array([10, 20, 30])


In [90]:
print(nn / mm) 

[[0.5  0.2  0.1 ]
 [0.4  0.25 0.2 ]]


In [91]:
print(nn * mm) 

[[ 50  80  90]
 [ 40 100 180]]


In [92]:
print(nn - mm) 

[[ -5 -16 -27]
 [ -6 -15 -24]]


In [93]:
print(nn ** mm) 

[[            9765625       1099511627776     205891132094649]
 [            1048576      95367431640625 8138741398091333632]]


---------------------

In [103]:
#import os 

In [102]:
#os.getcwd()

In [ ]:
#help(os.listdir)

In [ ]:
#os.listdir('.')

In [ ]:
#os.listdir('/usr')

# # ----------------------------------

# # TASK:


# #Step 1: Create a 2D array of shape (4, 4) filled with values 1-16 and print its shape and dtype.

In [97]:
arr1 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]])

In [98]:
print(arr1.shape)

(4, 4)


In [99]:
print(arr1.dtype)

int64


# # Step 2: Use slicing to extract the second column and the last row.

In [100]:
print(arr1[:, 1])

[ 2  6 10 14]


In [101]:
print(arr1[-1, :])

[13 14 15 16]


# #  Step 3: Use a boolean mask to select all values greater than the array's mean.

In [104]:
print(arr1.mean())

8.5


In [105]:
print(arr1 > arr1.mean())

[[False False False False]
 [False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [108]:
mask = arr1 > arr1.mean()

print(arr1[mask])

[ 9 10 11 12 13 14 15 16]


# #  Step 4: Add a 1D row array to every row of a 2D array using broadcasting, and verify the result manually.

In [ ]:
arr1 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]])
arr2 = np.array([4,4,4,4])
add = arr1 + arr2
print(add)

[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
